config/routes.rb
Rails.application.routes.draw do
  get 'student_details/index'

  resources :student_marks
  get 'static_pages/index'

  devise_for :users
  resources :students

  
  devise_scope :user do
    unauthenticated do
      root 'static_pages#index'
    end
    authenticated do
      root "students#index", as: :authenticated_user
    end
  end

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities

    if user.has_role? :admin
        can :manage, :all
    else
        can :read, :all
    end
  end
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles

  belongs_to :resource,
             :polymorphic => true

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/student.rb
class Student < ActiveRecord::Base
	has_one :student_mark, dependent: :destroy
	validates :roll, presence: true
	validates :sname, presence: true 


	has_attached_file :image,:storage => :s3, :s3_region=> 'us-east-1',
                    :s3_credentials => Proc.new{|a| a.instance.s3_credentials }

	validates_attachment :image
	validates_attachment_content_type :image, content_type: %w(image/jpeg image/jpg image/png)


	def s3_credentials
  	end
end

app/models/student_mark.rb
class StudentMark < ActiveRecord::Base
	belongs_to :student
	validates :student_id, presence: true
	validates :roll, presence: true
	validates :mark, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end
end

app/controllers/student_details_controller.rb
class StudentDetailsController < ApplicationController
  def index
  	@student_marks=StudentMark.where("mark>= ?", 50)

  end
end

app/controllers/student_marks_controller.rb
class StudentMarksController < ApplicationController
  before_action :set_student_mark, only: [:show, :edit, :update, :destroy]

  # GET /student_marks
  # GET /student_marks.json
  def index
    @student_marks = StudentMark.all
  end

  # GET /student_marks/1
  # GET /student_marks/1.json
  def show
  end

  # GET /student_marks/new
  def new
    @student_mark = StudentMark.new
  end

  # GET /student_marks/1/edit
  def edit
  end

  # POST /student_marks
  # POST /student_marks.json
  def create
    @student_mark = StudentMark.new(student_mark_params)

    respond_to do |format|
      if @student_mark.save
        format.html { redirect_to @student_mark, notice: 'Student mark was successfully created.' }
        format.json { render :show, status: :created, location: @student_mark }
      else
        format.html { render :new }
        format.json { render json: @student_mark.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /student_marks/1
  # PATCH/PUT /student_marks/1.json
  def update
    respond_to do |format|
      if @student_mark.update(student_mark_params)
        format.html { redirect_to @student_mark, notice: 'Student mark was successfully updated.' }
        format.json { render :show, status: :ok, location: @student_mark }
      else
        format.html { render :edit }
        format.json { render json: @student_mark.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /student_marks/1
  # DELETE /student_marks/1.json
  def destroy
    @student_mark.destroy
    respond_to do |format|
      format.html { redirect_to student_marks_url, notice: 'Student mark was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student_mark
      @student_mark = StudentMark.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_mark_params
      params.require(:student_mark).permit(:roll, :student_id, :mark)
    end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:create, :edit, :new, :destroy, :update]

  # GET /students
  # GET /students.json
  def index
    @students = Student.all
  end

  # GET /students/1
  # GET /students/1.json
  def show
    # redirect_to root_path
  end

  # GET /students/new
  def new
    @student = Student.new
    authorize! :new, @student

  end

  # GET /students/1/edit
  def edit
    authorize! :edit, @student
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(student_params)
    authorize! :create, @student

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: 'Student was successfully created.' }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    authorize! :update, @student
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    authorize! :destroy, @student
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: 'Student was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_params
      params.require(:student).permit(:sname, :age, :roll, :addr, :mobile, :email, :dob, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/student_details_helper.rb
module StudentDetailsHelper
end

app/helpers/student_marks_helper.rb
module StudentMarksHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Smis</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
<% if user_signed_in? %>
<%= link_to "sign_out", destroy_user_session_path, method: :delete %>
<% else %>
<%= link_to "sign_in", new_user_session_path %>
<%= link_to "sign_up", new_user_registration_path %>
<% end %>
<%= yield %>

</body>
</html>

app/views/static_pages/index.html.erb
<h1>StaticPages#index</h1>
<p>Find me in app/views/static_pages/index.html.erb</p>

app/views/student_details/index.html.erb
<%- model_class = StudentMark -%>
<div class="page-header">
  <h1>Student Details</h1>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:roll) %></th>
      <th><%= model_class.human_attribute_name(:student_id) %></th>
      <th><%= model_class.human_attribute_name(:mark) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
      
    </tr>
  </thead>
  <tbody>
    <% @student_marks.each do |student_mark| %>
      <tr>
        <td><%= link_to student_mark.id, student_mark_path(student_mark) %></td>
        <td><%= student_mark.roll %></td>
        <td><%= student_mark.student.sname %></td>
        <td><%= student_mark.mark %></td>
        <td><%=l student_mark.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_student_mark_path(student_mark), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      student_mark_path(student_mark),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_student_mark_path,
            :class => 'btn btn-primary' %>

app/views/student_marks/_form.html.erb
<%= form_for @student_mark, :html => { :class => "form-horizontal student_mark" } do |f| %>

    <% if @student_mark.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@student_mark.errors.count, "error") %> prohibited this student_mark from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @student_mark.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :roll, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :roll, :class => 'form-control' %>
    </div>
    <%= error_span(@student_mark[:roll]) %>
  </div>
  <div class="control-group">
    <%= f.label :student_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :student_id, :class => 'form-control' %>
    </div>
    <%= error_span(@student_mark[:student_id]) %>
  </div>
  <div class="control-group">
    <%= f.label :mark, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :mark, :class => 'form-control' %>
    </div>
    <%= error_span(@student_mark[:mark]) %>
  </div>


  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            student_marks_path, :class => 'btn btn-default' %>

<% end %>

app/views/student_marks/edit.html.erb
<%- model_class = StudentMark -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/student_marks/index.html.erb
<%- model_class = StudentMark -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:roll) %></th>
      <th><%= model_class.human_attribute_name(:student_id) %></th>
      <th><%= model_class.human_attribute_name(:mark) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @student_marks.each do |student_mark| %>
      <tr>
        <td><%= link_to student_mark.id, student_mark_path(student_mark) %></td>
        <td><%= student_mark.roll %></td>
        <td><%= student_mark.student.sname %></td>
        <td><%= student_mark.mark %></td>
        <td><%=l student_mark.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_student_mark_path(student_mark), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      student_mark_path(student_mark),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_student_mark_path,
            :class => 'btn btn-primary' %>

app/views/student_marks/new.html.erb
<%- model_class = StudentMark -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/student_marks/show.html.erb
<%- model_class = StudentMark -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:roll) %>:</strong></dt>
  <dd><%= @student_mark.roll %></dd>
  <dt><strong><%= model_class.human_attribute_name(:student_id) %>:</strong></dt>
  <dd><%= @student_mark.student_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:mark) %>:</strong></dt>
  <dd><%= @student_mark.mark %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              student_marks_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_student_mark_path(@student_mark), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              student_mark_path(@student_mark),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

app/views/students/_form.html.erb
<%= form_for @student, :html => { :class => "form-horizontal student" } do |f| %>

    <% if @student.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@student.errors.count, "error") %> prohibited this student from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @student.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :sname, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :sname, :class => 'form-control' %>
    </div>
    <%# error_span(@student[:sname]) %>
  </div>
  <div class="control-group">
    <%= f.label :age, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :age, :class => 'form-control' %>
    </div>
    <%# error_span(@student[:age]) %>
  </div>
  <div class="control-group">
    <%= f.label :roll, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :roll, :class => 'form-control' %>
    </div>
    <%# error_span(@student[:roll]) %>
  </div>
  <div class="control-group">
    <%= f.label :addr, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :addr, :class => 'form-control' %>
    </div>
    <%# error_span(@student[:addr]) %>
  </div>
  <div class="control-group">
    <%= f.label :mobile, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :mobile, :class => 'form-control' %>
    </div>
    <%# error_span(@student[:mobile]) %>
  </div>
  <div class="control-group">
    <%= f.label :email, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :email, :class => 'form-control' %>
    </div>
    <%# error_span(@student[:email]) %>
  </div>
  <div class="control-group">
    <%= f.label :dob, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :dob, :class => 'form-control' %>
    </div>
    <%# error_span(@student[:dob]) %>
  </div>

  <div>
    <%= f.label :image %>
    <%= f.file_field :image %>
  </div>




  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            students_path, :class => 'btn btn-default' %>

<% end %>

app/views/students/edit.html.erb
<div class="container">
	<div class="col-md-3">
		
	</div>
	<div class="col-md-6">
		<%- model_class = Student -%>
			<div class="page-header">
			  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
			</div>
			<%= render :partial => 'form' %>
	</div>
	<div class="col-md-3">
		
	</div>
</div>

app/views/students/index.html.erb
<%- model_class = Student -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:sname) %></th>
      <th><%= model_class.human_attribute_name(:age) %></th>
      <th><%= model_class.human_attribute_name(:roll) %></th>
      <th><%= model_class.human_attribute_name(:addr) %></th>
      <th><%= model_class.human_attribute_name(:mobile) %></th>
      <th><%= model_class.human_attribute_name(:email) %></th>
      <th><%= model_class.human_attribute_name(:dob) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= link_to student.id, student_path(student) %></td>
        <td><%= student.sname %></td>
        <td><%= student.age %></td>
        <td><%= student.roll %></td>
        <td><%= student.addr %></td>
        <td><%= student.mobile %></td>
        <td><%= student.email %></td>
        <td><%= student.dob %></td>
        <td><%=l student.created_at %></td>
        <td>

        <% if current_user && (current_user.has_role? :admin) %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_student_path(student), :class => 'btn btn-default btn-xs' %>
                      <!-- 
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      student_path(student),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'You can not delete before ...')) },
                      :class => 'btn btn-xs btn-danger' %> -->

          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      student_path(student),

                       onclick: "alert('You can not delete before....')",
                      :class => 'btn btn-xs btn-danger' %>            
        <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_student_path,
            :class => 'btn btn-primary' %>

app/views/students/new.html.erb
<%- model_class = Student -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/students/show.html.erb
<%- model_class = Student -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:sname) %>:</strong></dt>
  <dd><%= @student.sname %></dd>
  <dt><strong><%= model_class.human_attribute_name(:age) %>:</strong></dt>
  <dd><%= @student.age %></dd>
  <dt><strong><%= model_class.human_attribute_name(:roll) %>:</strong></dt>
  <dd><%= @student.roll %></dd>
  <dt><strong><%= model_class.human_attribute_name(:addr) %>:</strong></dt>
  <dd><%= @student.addr %></dd>
  <dt><strong><%= model_class.human_attribute_name(:mobile) %>:</strong></dt>
  <dd><%= @student.mobile %></dd>
  <dt><strong><%= model_class.human_attribute_name(:email) %>:</strong></dt>
  <dd><%= @student.email %></dd>
  <dt><strong><%= model_class.human_attribute_name(:dob) %>:</strong></dt>
  <dd><%= @student.dob %></dd>
</dl>

<div>
  <%= image_tag @student.image.url %>
</div>

<%= link_to t('.back', :default => t("helpers.links.back")),
              students_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_student_path(@student), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              student_path(@student),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>